### ISSUE TITLE
Doesn't seem to be working for me :(

### ISSUE THREAD

**Issue by CorePower** [lambwheit/KerboodleBookRipper#1]
![image](https://user-images.githubusercontent.com/26063173/93254614-83fd7a80-f790-11ea-8e15-0e1dbe615660.png)

**Comment by lambwheit** [comment]
do you mind sending the page name and image link?

**Comment by CorePower** [comment]
It happens with all links, even the default one

**Comment by lambwheit** [comment]
can you take a screenshot what your doing step by step and upload it to imgur as an album

**Comment by lambwheit** [comment]
https://imgur.com/upload

**Comment by lambwheit** [comment]
just tested the old example link it expired , will make a tut

**Comment by lambwheit** [comment]
https://imgur.com/a/5n3ZgWw

**Comment by lambwheit** [comment]
Created a small tutorial will include this into the readme, Hope this helped.
