### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by TeoPoulter** [lambwheit/KerboodleBookRipper#4]
I have no idea how to run this kind of code...which software do i use! please get in touch in discord (BG#1631) or here. ty!

**Comment by lambwheit** [comment]
u dont need to know the code, there is a precompiled version of this, it only runs on windows tho
https://github.com/lambwheit/KerboodleBookRipper/releases/tag/v2.0
download release.zip

**Comment by TeoPoulter** [comment]
I’m really confused...can I just give you my login and you can download the pdf of the book please? It’s faster than me getting confused and not being able to do any of this.
Username: ***@***.******@***.***>
Password: Buttermeup
ID: so4

I need this second book please! Tricolore book 2
***@***.***
Please respond with the pdf of the full book. tysm

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
