### ISSUE TITLE
Converting store file to pdf does not work

### ISSUE THREAD

**Issue by hypersonicstorm** [lambwheit/KerboodleBookRipper#6]
Hi, I'm not sure if this is just my problem, but attempting to convert a .store file into a pdf does not seem to work.

![image](https://github.com/lambwheit/KerboodleBookRipper/assets/73567298/78318f2c-4772-437b-bfed-865d9611c98f)
![image](https://github.com/lambwheit/KerboodleBookRipper/assets/73567298/d02194e6-fd8a-4ea3-9c5f-f430b86aa65c)

Does anyone know what's going on? The .store file seems to be fine. Any help would be appreciated!

**Comment by lambwheit** [comment]
can you send the .store file, i'll take a look at it tmr

**Comment by hypersonicstorm** [comment]
[chemstore.zip](https://github.com/lambwheit/KerboodleBookRipper/files/12775335/chemstore.zip)
for now I just made a really simple (and probably quite bad) python program to do it
![image](https://github.com/lambwheit/KerboodleBookRipper/assets/73567298/ff71138a-e233-4081-8081-d7afa8b674ff)

**Comment by lambwheit** [comment]
found the problem it's something to with the tls thing, i'll fix it and close the ticket when i have the next release uploaded.

**Comment by lambwheit** [comment]
fixed in latest release: https://github.com/lambwheit/KerboodleBookRipper/releases/tag/v2.1
